name: Progress
on: push
jobs:
    update-progress:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
            with:
                fetch-depth: "0"
          - uses: actions/setup-go@v3
            with:
                go-version: '1.18'
                check-latest: true
          - run: go run cmd/progress/main.go . progress-report
          - uses: peaceiris/actions-gh-pages@v3
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: progress-report